let quiz=[],current=0,score=0,answered=false,timer=null,timeLeft=20,mode='classic',teamA=0,teamB=0,lang=localStorage.getItem('traditionsLang')||'fr';const TOTAL=10,app=document.getElementById('app');
function T(k){return UI[lang][k]||UI.fr[k]||k}
function L(obj){return obj&&typeof obj==='object'?(obj[lang]||obj.fr||obj.en||Object.values(obj)[0]):String(obj||'')}
function shuffle(a){const arr=[...a];for(let i=arr.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[arr[i],arr[j]]=[arr[j],arr[i]]}return arr}
function pick(){return shuffle(QUESTIONS_VERIFIED_30).slice(0,TOTAL)}
function langButtons(){return `<div class="langs">${['fr','en','nl'].map(l=>`<button class="${lang===l?'active':''}" data-lang="${l}">${l.toUpperCase()}</button>`).join('')}</div>`}
function bindLang(){document.querySelectorAll('[data-lang]').forEach(b=>b.onclick=()=>{lang=b.dataset.lang;localStorage.setItem('traditionsLang',lang);quiz.length?render():home()})}
function topBar(){return `<div class="top"><img class="corLogo" src="assets/CoR_logo.png" alt="CoR logo"><h1 class="mainTitle">${T('title')}</h1>${langButtons()}</div>`}
function home(){clearInterval(timer);quiz=[];current=0;score=0;answered=false;app.innerHTML=`<div class="shell"><div class="stage">${topBar()}<div class="content homeContent"><div><h2 class="headline">${T('homeTitle')}</h2><p class="subtitle">${T('homeSub')}</p><div class="modeRow"><button class="modeBtn ${mode==='classic'?'active':''}" data-mode="classic">${T('classic')}</button><button class="modeBtn ${mode==='teams'?'active':''}" data-mode="teams">${T('teams')}</button></div><div class="smallNote">${T('note')}</div></div><div class="startPanel"><div class="duelPreview"><div class="duelBtn">A</div><div class="duelBtn">B</div></div><button id="start" class="primary blueBtn">${T('start')}</button></div></div><div class="footer"><span>${T('footerStart')}</span><span>${T('footerResult')}</span></div></div></div>`;bindLang();document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>x.classList.remove('active'));b.classList.add('active')});document.getElementById('start').onclick=start}
function start(){quiz=pick();current=0;score=0;teamA=0;teamB=0;render()}
function render(){clearInterval(timer);answered=false;const q=quiz[current];app.innerHTML=`<div class="shell"><div class="stage">${topBar()}<div class="content"><div class="status"><div class="pill">${T('question')} ${current+1} ${T('of')} ${quiz.length}</div><div class="pill">${T('score')}: <strong>${score}</strong></div><div class="pill timer" id="timerBox">20</div></div><div class="progress"><div style="width:${(current/quiz.length)*100}%"></div></div>${mode==='teams'?`<div class="teamScores"><button id="teamA">${T('teamA')}: ${teamA}</button><button id="teamB">${T('teamB')}: ${teamB}</button></div>`:''}<h2 class="scenarioText">${L(q.scenario)}</h2><p class="questionText">${L(q.question)}</p><div class="answers" id="answers"></div><div id="feedback" class="feedback hidden"></div><div class="nextArea"><button id="nextButton" class="primary hidden">${current+1===quiz.length?T('result'):T('next')}</button></div></div><div class="footer"><span>${T('title')}</span><span>${T('footerQuiz')}</span></div></div></div>`;bindLang();if(mode==='teams'){document.getElementById('teamA').onclick=()=>{teamA++;document.getElementById('teamA').textContent=`${T('teamA')}: ${teamA}`};document.getElementById('teamB').onclick=()=>{teamB++;document.getElementById('teamB').textContent=`${T('teamB')}: ${teamB}`}}const box=document.getElementById('answers');shuffle(q.answers[lang]).forEach((a,i)=>{const btn=document.createElement('button');btn.className='answer';btn.textContent=String.fromCharCode(65+i)+'. '+a;btn.onclick=()=>reveal(a);box.appendChild(btn)});document.getElementById('nextButton').onclick=next;startTimer()}
function startTimer(){timeLeft=20;timer=setInterval(()=>{timeLeft--;const el=document.getElementById('timerBox');if(el)el.textContent=timeLeft;if(timeLeft<=0){clearInterval(timer);reveal(null)}},1000)}
function reveal(sel){if(answered)return;answered=true;clearInterval(timer);const q=quiz[current],correct=L(q.correctAnswer),ok=sel===correct;if(ok)score++;document.querySelectorAll('.answer').forEach(btn=>{btn.disabled=true;btn.classList.add('disabled');if(btn.textContent.includes(correct))btn.classList.add('correct');if(sel&&btn.textContent.includes(sel)&&!ok)btn.classList.add('wrong')});const fb=document.getElementById('feedback');fb.innerHTML=`<strong>${sel===null?T('timeout'):ok?T('correct'):T('wrong')}.</strong><br><strong>${T('tradName')} :</strong> ${L(q.traditionName)}<br><strong>${T('country')} :</strong> ${correct}<br><strong>${T('region')} :</strong> ${L(q.region)}<br>${L(q.explanation)}<div class="sourceLink">${T('source')}: <a href="${q.sourceUrl}" target="_blank" rel="noopener">${q.sourceName}</a></div>`;fb.classList.remove('hidden');document.getElementById('nextButton').classList.remove('hidden')}
function next(){current<quiz.length-1?(current++,render()):results()}
function results(){clearInterval(timer);const pct=Math.round(score/quiz.length*100);app.innerHTML=`<div class="shell"><div class="stage">${topBar()}<div class="content" style="text-align:center"><h2 class="headline">${T('finished')}</h2><p class="subtitle">${T('finalScore')}</p><div class="finalScore">${score} / ${quiz.length}</div><p class="subtitle">${pct}%</p><button id="restart" class="primary blueBtn">${T('restart')}</button></div><div class="footer"><span>${T('footerStart')}</span><span>${T('footerResult')}</span></div></div></div>`;bindLang();document.getElementById('restart').onclick=start}
document.addEventListener('DOMContentLoaded',home);