const LANGS=['FR'];
let quiz=[],current=0,score=0,answered=false,timer=null,timeLeft=20,mode='classic',teamA=0,teamB=0;
const TOTAL=30;
const app=document.getElementById('app');
function safeText(v){if(v===null||v===undefined)return ''; if(typeof v==='string'||typeof v==='number')return String(v); if(typeof v==='object')return v.fr||v.en||Object.values(v).find(x=>typeof x==='string')||''; return String(v)}
function shuffle(a){const arr=[...(Array.isArray(a)?a:[])];for(let i=arr.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[arr[i],arr[j]]=[arr[j],arr[i]]}return arr}
function normalise(raw){return {id:safeText(raw.id),country:safeText(raw.country),region:safeText(raw.region),theme:(raw.tags&&raw.tags[0])?safeText(raw.tags[0]):safeText(raw.difficulty),difficulty:safeText(raw.difficulty),scenario:safeText(raw.scenario_fr),question:safeText(raw.question_fr),answers:(Array.isArray(raw.answers_fr)?raw.answers_fr:[]).map(safeText).filter(Boolean),correctAnswer:safeText(raw.correctAnswer_fr),explanation:safeText(raw.explanation_fr),status:safeText(raw.verificationStatus),traditionName:safeText(raw.traditionName)}}
function pick(){const selected=[], countryCounts={}; for(const q of shuffle(QUESTIONS_400).map(normalise)){if(!q.scenario||q.answers.length!==4||!q.correctAnswer)continue; if((countryCounts[q.country]||0)>=2)continue; selected.push(q); countryCounts[q.country]=(countryCounts[q.country]||0)+1; if(selected.length===TOTAL)break} if(selected.length<TOTAL){for(const q of shuffle(QUESTIONS_400).map(normalise)){if(selected.find(x=>x.id===q.id))continue; if(!q.scenario||q.answers.length!==4||!q.correctAnswer)continue; selected.push(q); if(selected.length===TOTAL)break}} return shuffle(selected)}
function topBar(){return `<div class="top"><div class="logoBox"><img class="corLogo" src="assets/CoR_logo.png" alt="CoR logo"></div><h1 class="mainTitle">Europe’s Traditions Challenge</h1><div class="langs"><button class="active" type="button">FR</button></div></div>`}
function home(){clearInterval(timer);quiz=[];current=0;score=0;answered=false;app.innerHTML=`<div class="shell"><div class="stage">${topBar()}<div class="content homeContent"><div><h2 class="headline">30 questions tirées d’une base de 400 traditions</h2><p class="subtitle">Des scénarios courts, visuels et amusants. Le joueur devine le pays parmi 4 réponses.</p><div class="modeRow"><button type="button" class="modeBtn ${mode==='classic'?'active':''}" data-mode="classic">Classique</button><button type="button" class="modeBtn ${mode==='teams'?'active':''}" data-mode="teams">Duel équipes</button></div><div class="smallNote">Tirage aléatoire à chaque partie · maximum 2 questions par pays.</div></div><div class="startPanel"><div class="duelPreview"><div class="duelBtn">A</div><div class="duelBtn">B</div></div><button id="start" class="primary blueBtn" type="button">Lancer le challenge</button></div></div><div class="footer"><span>CoR gamification prototype V3 · 400 traditions intégrées</span><span>GitHub Pages ready</span></div></div></div>`;document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>x.classList.remove('active'));b.classList.add('active')});document.getElementById('start').onclick=start}
function start(){quiz=pick();current=0;score=0;teamA=0;teamB=0;if(!quiz.length){errorScreen();return}render()}
function errorScreen(){app.innerHTML=`<div class="shell"><div class="stage">${topBar()}<div class="content"><h2 class="headline">Erreur de chargement des questions</h2><p>Aucune question valide trouvée dans questions-400.js.</p><button class="primary blueBtn" onclick="home()">Retour</button></div></div></div>`}
function render(){clearInterval(timer);answered=false;const q=quiz[current];app.innerHTML=`<div class="shell"><div class="stage">${topBar()}<div class="content"><div class="status"><div class="pill">Question ${current+1} sur ${quiz.length}</div><div class="pill">Score: <strong>${score}</strong></div><div class="pill timer" id="timerBox">20</div></div><div class="progress"><div style="width:${(current/quiz.length)*100}%"></div></div>${mode==='teams'?`<div class="teamScores"><button id="teamA" type="button">Équipe A: ${teamA}</button><button id="teamB" type="button">Équipe B: ${teamB}</button></div>`:''}<div class="meta"><span>${q.country}</span><span>${q.theme}</span><span>${q.difficulty}</span></div><h2 class="scenarioText">${q.scenario}</h2><p class="questionText">${q.question}</p><div class="answers" id="answers"></div><div id="feedback" class="feedback hidden"></div><div class="nextArea"><button id="nextButton" class="primary hidden" type="button">${current+1===quiz.length?'Résultat':'Question suivante'}</button></div></div><div class="footer"><span>${q.traditionName}</span><span>${q.status==='to_verify'?'À sourcer avant publication finale':'Question de départ vérifiée à recontrôler'}</span></div></div></div>`; if(mode==='teams'){document.getElementById('teamA').onclick=()=>{teamA++;document.getElementById('teamA').textContent=`Équipe A: ${teamA}`};document.getElementById('teamB').onclick=()=>{teamB++;document.getElementById('teamB').textContent=`Équipe B: ${teamB}`}} const box=document.getElementById('answers');shuffle(q.answers).forEach((a,i)=>{const btn=document.createElement('button');btn.className='answer';btn.type='button';btn.textContent=String.fromCharCode(65+i)+'. '+a;btn.onclick=()=>reveal(a);box.appendChild(btn)});document.getElementById('nextButton').onclick=next;startTimer()}
function startTimer(){timeLeft=20;const el=document.getElementById('timerBox');if(el)el.textContent=timeLeft;timer=setInterval(()=>{timeLeft--;const live=document.getElementById('timerBox');if(live)live.textContent=timeLeft;if(timeLeft<=0){clearInterval(timer);reveal(null)}},1000)}
function reveal(selected){if(answered)return;answered=true;clearInterval(timer);const q=quiz[current];const ok=selected===q.correctAnswer;if(ok)score++;document.querySelectorAll('.answer').forEach(btn=>{btn.classList.add('disabled');btn.disabled=true;if(btn.textContent.includes(q.correctAnswer))btn.classList.add('correct');if(selected&&btn.textContent.includes(selected)&&!ok)btn.classList.add('wrong')});const fb=document.getElementById('feedback');fb.innerHTML=`<strong>${selected===null?'Temps écoulé':ok?'Correct':'Incorrect'}.</strong><br>Réponse: <strong>${q.correctAnswer}</strong><br>${q.explanation}`;fb.classList.remove('hidden');document.getElementById('nextButton').classList.remove('hidden')}
function next(){current<quiz.length-1?(current++,render()):results()}
function results(){clearInterval(timer);const pct=Math.round(score/quiz.length*100);app.innerHTML=`<div class="shell"><div class="stage">${topBar()}<div class="content" style="text-align:center"><h2 class="headline">Challenge terminé</h2><p class="subtitle">Score final</p><div class="finalScore">${score} / ${quiz.length}</div><p class="subtitle">${pct}%</p><button id="restart" class="primary blueBtn" type="button">Rejouer</button></div><div class="footer"><span>CoR gamification prototype V3</span><span>Base de 400 traditions intégrée</span></div></div></div>`;document.getElementById('restart').onclick=start}
document.addEventListener('DOMContentLoaded',home);